<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TwitchLib.Client" Version="3.4.0" />
    <PackageReference Include="TwitchLib.EventSub.Websockets" Version="0.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChatProvider\ChatProvider.csproj" />
  </ItemGroup>

</Project>
